let obj = {
	"path": [{
		"path": "infoChange",
		"breadcrumbName": "會員資料查詢"
	}],
	"changeArr": [{
		"title": "客戶身分",
		"type": "input",
		"key": "custIdentity",
		disabled: true,
		error: false,
		required: false,
		"items": ""
	}, {
		"title": "會員編號",
		"type": "input",
		disabled: true,
		"key": "accountCode",
		regular: 'name',
		error: false,
		required: false,
		"items": ""
	}, {
		"title": "身份證字號",
		disabled: true,
		"type": "input",
		"key": "certificateNo",
		"items": "",
		error: false,
		required: false,
		regular: 'part',
	}, {
		"title": "姓名",
		"type": "input",
		"key": "name",
		regular: 'name',
		errorMsg: '姓名請至少填寫2個中文或4個英文',
		error: false,
		required: false,
		"items": ""
	}, {
		"title": "生日",
		"type": "time",
		required: false,
		"key": "birthday",
		value: "",
	}, {
		"title": "手機",
		"type": "input",
		"key": "phone",
		regular: 'phone',
		required: false,
		error: false,
		"items": ""
	}, {
		"title": "E-mail",
		"type": "input",
		"key": "email",
		regular: 'email',
		required: false,
		error: false,
		"items": ""
	}, {
		"title": "推薦人會員編號",
		"type": "input",
		"key": "referrerCode",
		regular: 'email',
		required: false,
		error: false,
		"items": ""
	}, {
		"title": "會員註冊日期",
		"type": "input",
		"key": "registerTimeStr",
		disabled: true,
		regular: 'email',
		required: false,
		error: false,
		"items": ""
	}, {
		"title": "註冊通路",
		"type": "input",
		"key": "channelName",
		disabled: true,
		regular: 'email',
		required: false,
		error: false,
		"items": ""
	}, {
		"title": "Media Code",
		"type": "input",
		"key": "mediaCode",
		disabled: true,
		regular: 'email',
		required: false,
		error: false,
		"items": ""
	}, {
		title: "會員狀態",
		type: "radio",
		key: "status",
		width: "100%",
		value: "",
		"items": [{
		    "name": "開啟",
		    "value": '00'
		}, {
		    "name": "註銷",
		    "value": '01'
		}]
	}, {
		title: "備註",
		type: "textarea",
		key: "remarks",
		width: "100%",
		value: "",
		items: ""
	}],
	"searchArr": [{
		"title": "姓名",
		"type": "input",
		"key": "name",
		size: 30,
		"items": ""
	}, {
		"title": "身份證字號",
		"type": "input",
		"key": "certificateNo",
		size: 10,
		"items": ""
	}, {
		"title": "會員帳號",
		"type": "input",
		"key": "accountCode",
		size: 7,
		"items": ""
	}, {
		"title": "手機",
		"type": "input",
		"key": "phone",
		size: 10,
		"items": ""
	}, {
		"title": "E-mail ",
		"type": "input",
		"key": "email",
		size: 50,
		"items": ""
	}, {
		"title": "異動日期",
		"type": "rangeTime",
		"key": "DateRange",
		
	}, {
		"title": "狀態",
		"type": "select",
		"key": "status",
		"items": [{
			"name": "全部",
			"value": ''
		}, {
			"name": "開啓",
			"value": '00'
		}, {
			"name": "關閉",
			"value": '01'
		}]
	}, {
		"title": "通路名稱",
		"type": "select",
		"key": "channelCode",
		width: "200px",
		"items": ""
	}],
	"columns": [{
		"title": "會員編號",
		"dataIndex": "accountCode",
		"fixed": ""
	}, {
		"title": "姓名",
		"dataIndex": "name",
		// width: 100,
		"fixed": ""
	}, {
		"title": "身份證字號",
		"dataIndex": "certificateNo",
		"fixed": ""
	}, {
		"title": "生日",
		"dataIndex": "birthday",
		"fixed": ""
	}, {
		"title": "手機",
		"dataIndex": "phone",
		"fixed": ""
	}, {
		"title": "E-mail",
		"dataIndex": "email",
		"fixed": ""
	}, {
		"title": "推薦人會員編號",
		"dataIndex": "referrerCode",
		"fixed": ""
	}, {
		"title": "通路名稱",
		"dataIndex": "channelName",
		"fixed": ""
	}, {
		"title": "Media Code",
		"dataIndex": "mediaCode",
		"fixed": ""
	}, {
		"title": "異動日期",
		"dataIndex": "updateTimeStr",
		"fixed": ""
	}, {
		title: "審核狀態",
		"dataIndex": "auditorStatusStr",
		"fixed": "",
		// scopedSlots: {
		// 	customRender: "other"
		// }
	}, {
		title: "操作",
		key: "operation",
		"fixed": "right",
		width: 200,
		align: 'right',
		scopedSlots: {
			customRender: "operation"
		}
	}],
	"columnsOther": [{
		"title": "姓名",
		"dataIndex": "name",
		"fixed": ""
	}, {
		"title": "身份證字號",
		"dataIndex": "certificateNo",
		"fixed": ""
	}, {
		"title": "生日",
		"dataIndex": "birthday",
		scopedSlots: {
			customRender: 'other'
		},
		"fixed": ""
	}, {
		"title": "手機",
		"dataIndex": "phone",
		scopedSlots: {
			customRender: 'other'
		},
		"fixed": ""
	}, {
		"title": "E-mail ",
		"dataIndex": "email",
		scopedSlots: {
			customRender: 'other'
		},
		"fixed": ""
	}, {
		"title": "推薦人會員編號",
		"dataIndex": "referrerCode",
		scopedSlots: {
			customRender: 'other'
		},
		"fixed": ""
	}, {
		"title": "狀態",
		"dataIndex": "statusStr",
		scopedSlots: {
			customRender: 'other'
		},
		"fixed": ""
	}, {
		title: "異動時間/異動人員帳號",
		key: "others",
		"fixed": "",
		scopedSlots: {
			customRender: "others"
		}
	}, {
		title: "審核時間/審核人帳號",
		key: "operation",
		"fixed": "right",
		scopedSlots: {
			customRender: "operation"
		}
	}]
}
export default obj
