let obj = {
    "path": [{
        "path": "allInsure",
        "breadcrumbName": "所有投保紀錄查詢"
    }],
    "changeArr": [],
    "searchArr": [{
        "title": "要(被)保人身分證字號",
        "type": "input",
        size: 10,
        "key": "certificateNo",
        "items": ""
    }, {
        "title": "要(被)保人姓名",
        "type": "input",
        size: 30,
        "key": "appName",
        "items": ""
    }, {
        "title": "訂單編號",
        "type": "input",
        "key": "orderNo",
        size: 10,
        "items": ""
    }, {
        "title": "商品名稱",
        "type": "select",
        "key": "goodsId",
        width: "240px",
        "items": []
    }, {
        "title": "訂單狀態",
        "type": "select",
        "key": "orderStatus",
        "items": [{
            "name": "投保資格確認",
            "value": 1
        }, {
            "name": "資料填寫",
            "value": 2
        }, {
            "name": "資料確認",
            "value": 3
        }, {
            "name": "待繳費",
            "value": 4
        }, ]
    }, {
        "title": "訂單產生日",
        "type": "rangeTime",
        "key": "DateRange",
    }],
    "columns": [{
        "title": "訂單編號",
        "dataIndex": "orderNo",
        "fixed": ""
    }, {
        "title": "要保人姓名",
        "dataIndex": "appName",
        "fixed": ""
    }, {
        "title": "訂單產生日",
        "dataIndex": "orderDateStr",
        "fixed": ""
    }, {
        "title": "被保人姓名",
        "dataIndex": "insuName",
        "fixed": ""
    }, {
        "title": "商品名稱",
        "dataIndex": "goodsName",
        "fixed": ""
    }, {
        "title": "保險金額(元)",
        "dataIndex": "amountStr",
        "fixed": "",
        align: 'right'
    }, {
        "title": "保費(元)",
        "dataIndex": "orderAmountStr",
        "fixed": "",
        align: 'right'
    }, {
        "title": "訂單狀態",
        "dataIndex": "orderStatusStr",
        "fixed": ""
    }, {
        title: "操作",
        key: "operation",
        "fixed": "right",
        width: 100,
        scopedSlots: {
            customRender: "operation"
        }
    }]
}
export default obj